# Generated by Django 4.2.3 on 2023-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TK', 'Танк'), ('HL', 'Лекарь'), ('DD', 'Урон'), ('TR', 'Торговец'), ('GM', 'Гильдмастер'), ('QG', 'Квестгивер'), ('BS', 'Кузнец'), ('TN', 'Кожевник'), ('PT', 'Зельевар'), ('MG', 'Мастер заклинаний'), ('NO', 'Нет класса')], default='NO', max_length=2, verbose_name='Класс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
