# Generated by Django 4.2.3 on 2023-07-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
    ]
